rdkcentral/entservices-apis

- apis/RDKWindowManager/IRDKWindowManager.h
Reason for change : event apis are converted to have default handling
Test Procedure: tested JsonRPC and ComRPC interface at RDKE MW layer level
Risks: Medium
Priority: P2
Signed-off-by: Dali Hariharan bp-dharih957@cable.comcast.com
> RDKEMW-1810 update apis to have default handling

- apis/Ids.h
- apis/UserSettings/IUserSettings.h
Reason for change: Added user settings inspector interface to user settings plugin.
Test Procedure: Make full stack build and verify user settings inspector interface.
https://etwiki.sys.comcast.net/display/RDKV/User+Settings+Inspector
Risks: Low
Priority: P1
> RDK-56276: Add user settings inspector interface to user settings plugin

- apis/Ids.h
- apis/StorageManager/IStorageManager.h
Reason for change : Create Interface File for StorageManager , for clear and clearAll just support JSON-RPC
Test Procedure: Compilation is fine
Risks: Medium
Priority: P2
Signed-off-by: Madhumathi R bp-mbhand796@cable.comcast.com
> RDKEMW-2019 : StorageManager API Declaration

- README.md
- governance.md
Reason for change : Documentation Update
Test Procedure: Verify the documentation update is successful
Risks: Low
Signed-off-by: Soundaryaa Sitaram<Soundaryaa_Sitaram@comcast.com>
> RDKEMW-1691 : Update governance document

- .github/workflows/Validate_Interface_headers_incremental.yml
- .github/workflows/validate_interface_headers_incremental.py
- apis/Ids.h
- apis/UserSettings/IUserSettings.h
> RDKEMW-2257 : new workflow to detect interface guidelines errors

- apis/UserSettings/IUserSettings.h
Reason for change: Added user settings inspector interface to user settings plugin.
Test Procedure: Make full stack build and verify user settings inspector interface.
https://etwiki.sys.comcast.net/display/RDKV/User+Settings+Inspector
Risks: Low
Priority: P1
Signed-off-by: bp-ndosak198@cable.comcast.com
> RDK-56276: Add user settings inspector interface to user settings plugin.

- docs/apis/UserSettingsPlugin.md
- tools/json_generator/output/UserSettings/UserSettings.json
Reason for change:
RDKEMW-2483: Out of range values are accepted by org.rdk.UserSettings.setVoiceGuidanceRate api.
RDK-56276: Updated version numbers and changelog.md and documentation
Test Procedure: Make full stack build and verify user settings setVoiceGuidanceRate api.
https://etwiki.sys.comcast.net/display/RDKV/User+Settings+Inspector
Risks: Low
Priority: P1
> RDKEMW-2483: Out of range values are accepted by org.rdk.UserSettings setVoiceGuidanceRate api

- apis/AmazonPrime/IAmazonPrime.h
- apis/Ids.h
Reason for change:
Add Amazon Prime plugin interfaces to wpeframework
Risks: None
> PREMIUMAPP-3182: Add Amazon Prime plugin interfaces

- apis/PowerManager/IPowerManager.h
RDK-57093: PowerManager Interface file modified
Reason for changes: The Interface method return type and event APIs are modified as per API spec
Test procedure: Full stack build
Risk: Low
> RDK-57093: PowerManager Interface methods and event APIs modified

- apis/USBDevice/IUSBDevice.h
- apis/USBMassStorage/IUSBMassStorage.h
- apis/UserSettings/IUserSettings.h
- docs/apis/USBDevicePlugin.md
- docs/apis/USBMassStoragePlugin.md
- tools/json_generator/output/USBDevice/USBDevice.json
- tools/json_generator/output/USBMassStorage/USBMassStorage.json
Reason for change: UsbPlugins documentation and middleware updates.
Test Procedure: Make full stack build and run Usb plugins curl commands.  
https://etwiki.sys.comcast.net/pages/viewpage.action?spaceKey=RDKV&title=USB+Device
https://etwiki.sys.comcast.net/display/RDKV/USB+Mass+Storage
Risks: Medium
Priority: P1
> RDKEMW-2907: USBPlugins Updates

- apis/NativeJS/INativeJS.h
RDKEMW-3925: Updating the interface API's  
Reason for change: Cleaned up the code
Test Procedure: build should be successful.
Risks: low
Priority: P2
> RDKEMW-3925: Update rdkNativeScript with application identifiers

- apis/UserSettings/IUserSettings.h
Reason for change:  Added new property content Pin in User settings
Test Procedure: Run curl commands on box and test the content Pin. refer below page.
https://etwiki.sys.comcast.net/pages/viewpage.action?spaceKey=RDKV&title=User+Settings
Risks: NO
Priority: P1
> RDK-57748: Add new property in contentPin in Usersettings

- apis/AppManager/IAppManager.h
Reverts rdkcentral/entservices-apis#213
> Revert "RDKEMW-3886 : [AppManager] Events registration"

- docs/apis/UserSettingsPlugin.md
- tools/json_generator/output/UserSettings/UserSettings.json
Reason for change: Updated version details.
Test Procedure: no
Risks: NO
Priority: P1
> RDK-57747: Updated version details.

- apis/common.json
- docs/apis/FrameRatePlugin.md
Reason for Change: Update FrameRate plugin documentation to match current implementation
> RDK-55551-RDKEMW-1012: update FrameRate plugin documentation (#338)

- docs/apis/LEDControlPlugin.md
- tools/json_generator/output/LEDControl/LEDControl.json
Reason for change: Updated the document as per latest result 
Test Procedure: None
Priority: P2
Signed-off-by:Dineshkumar P dinesh_kumar2@comcast.com
> RDKEMW-5807 Update the LEDControl plugin entservice-apis doc

- docs/apis/SharedStoragePlugin.md
- tools/json_generator/output/SharedStorage/SharedStorage.json
- tools/json_generator/output/SharedStorage/SharedStoragePlugin.json
Reason for change: Created the SharedStorage plugin entservice-apis doc Test Procedure: None
Risks: Low
Priority: P2
Signed-off-by:Dineshkumar P dinesh_kumar2@comcast.com
> RDKEMW-6142: Create the SharedStorage plugin entservice-apis doc

- apis/RDKWindowManager/IRDKWindowManager.h
Reason for change: Add onConnected onFocus,onBlur,onVisible and onHidden events
Test Procedure: Validation done via prints
Risks: Low
Priority: P2
Signed-off-by: bp-pviswa149@cable.comcast.com
> RDKEMW-5480: Add events in RDK WM Thunder Plugin

- apis/RDKWindowManager/IRDKWindowManager.h
Reason For change: IRDKWindowManager.setZOrder And IRDKWindowManager.getZOrder
Risks: Medium
Priority: P1
Signed-off-by: Madhumathi R bp-mbhand796@cable.comcast.com
> RDKEMW-5487: Implement setZorder and getZorder

- docs/apis/XCastPlugin.md
- tools/json_generator/output/XCast/XCast.json
RDKEMW-6941: Update Xcast API documentation
Signed-off-by: yuvaramachandran_gurusamy <yuvaramachandran_gurusamy@comcast.com>
> RDKEMW-6941: Update Xcast API documentation

- apis/AppManager/IAppManager.h
Reason for change: Add check for wrong values.
Test Procedure: verified
Risks: Low
Priority: P1
Signed-off-by: Sourav Dutta bp-sdutta290@cable.comcast.com
> RDKEMW-7851 : [AI2.0] Add check for wrong values

- apis/AppManager/IAppManager.h
Reason for change: Add check for wrong values.
Test Procedure: verified
Risks: Low
Priority: P1
Signed-off-by: Sourav Dutta [bp-sdutta290@cable.comcast.com](mailto:bp-sdutta290@cable.comcast.com)
> RDKEMW-7851 : [AI2.0] Add check for wrong values 
